// common
export const APP_LOAD = 'APP_LOAD'
export const REDIRECT = 'REDIRECT'
export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED'
export const HOME_PAGE_UNLOADED = 'HOME_PAGE_UNLOADED'
export const ADD_COMMENT = 'ADD_COMMENT'
export const SET_PAGE = 'SET_PAGE'
export const APPLY_TAG_FILTER = 'APPLY_TAG_FILTER'
export const CHANGE_TAB = 'CHANGE_TAB'
export const UPDATE_FIELD_AUTH = 'UPDATE_FIELD_AUTH'
export const UPDATE_FIELD_EDITOR = 'UPDATE_FIELD_EDITOR'
export const FOLLOW_USER = 'FOLLOW_USER'
export const UNFOLLOW_USER = 'UNFOLLOW_USER'
export const ASYNC_START = 'ASYNC_START'
export const ASYNC_END = 'ASYNC_END'
export const CHANGE_FIELD = 'UPDATE_FIELD'
export const BLUR_FIELD = 'BLUR_FIELD'
export const REGISTER_PAGE_UNLOADED = 'REGISTER_PAGE_UNLOADED'
export const EDITOR_PAGE_UNLOADED = 'EDITOR_PAGE_UNLOADED'


// auth
export const LOGIN_PAGE_UNLOADED = 'LOGIN_PAGE_UNLOADED'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const REGISTER = 'REGISTER'
export const LOAD_USER = 'LOAD_USER'
export const AUTH_USER_SET = 'AUTH_USER_SET'


// user
export const BLUR_SETTINGS_FIELD = 'BLUR_SETTINGS_FIELD'
export const CHANGE_SETTINGS_FIELD = 'CHANGE_SETTINGS_FIELD'
export const SETTINGS_SAVED = 'SETTINGS_SAVED'
export const PROFILE_PAGE_LOADED = 'PROFILE_PAGE_LOADED'


// present
export const LOAD_PRESENTS = 'LOAD_PRESENTS'
export const EDIT_PRESENT_FORM_LOAD = 'EDIT_PRESENT_FORM_LOAD'
export const ADD_PRESENT_FORM_LOAD = 'ADD_PRESENT_FORM_LOAD'
export const CHANGE_SEARCH_PRESENT = 'CHANGE_SEARCH_PRESENT'
export const FILTER_VISIBILITY = 'FILTER_VISIBILITY'
export const SEARCH_PRESENT = 'SEARCH_PRESENT'
export const GET_PRESENT_FROM_STORE = 'GET_PRESENT_FROM_STORE'
export const GET_PRESENT_FROM_API = 'GET_PRESENT_FROM_API'
export const DELETE_PRESENT = 'DELETE_PRESENT'
export const ADD_PRESENT = 'ADD_PRESENT'
export const EDIT_PRESENT = 'EDIT_PRESENT'


// tag
export const GET_TAGS = 'GET_TAGS'
export const ADD_TAG = 'ADD_TAG'
export const REMOVE_TAG = 'REMOVE_TAG'
